services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
